printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid


#  "lint": "eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0",